# Base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json dan lock file
COPY package.json ./
COPY package-lock.json ./ 

# Install dependencies
RUN npm install  

# Copy semua file ke dalam container
COPY . .

# Build aplikasi Svelte
RUN npm run build

# Install server statis buat serve build
RUN npm install -g serve

# Expose port untuk aplikasi
EXPOSE 3000

# Jalankan aplikasi menggunakan server statis
CMD ["serve", "-s", "public/build", "-l", "3000"]