version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/backend/app 
    env_file:
      - ./backend/.env
    depends_on:
      - model

  model:
    build: ./model-container
    ports:
      - "5000:5000"  # Port buat inference model
    volumes:
      - ./model-container/app:/model-container/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000  
    depends_on:
      - backend
