# Stage 1: Build stage
FROM python:3.12-slim AS build

# Set working directory
WORKDIR /backend

# Install curl and build-essential
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install uv package manager
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh


# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin:$PATH"
ENV PATH="/root/.cargo/bin:$PATH"

# Copy pyproject.toml and uv.lock to the working directory
COPY pyproject.toml uv.lock /backend/

# Install dependencies using uv
RUN uv sync --frozen --no-install-project --no-dev

# Stage 2: Runtime stage
FROM python:3.12-slim AS runtime

# Set working directory
WORKDIR /backend

# Copy dependencies from the build stage
COPY --from=build /backend /backend

# Set environment variables
ENV PATH="/backend/.venv/bin:$PATH"

# Expose port for FastAPI
EXPOSE 8000

# Run the FastAPI server on workdir/app/main.py
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]